apiVersion: 1

datasources:
  # Configuración de Loki (Logs)
  - name: Loki
    type: loki
    uid: loki-ds
    access: proxy
    url: http://loki:3100
    jsonData:
      # Este bloque crea el enlace automático de Log -> Traza
      derivedFields:
        - datasourceUid: tempo-ds
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: '$${__value.raw}'

  # Configuración de Tempo (Trazas)
  - name: Tempo
    type: tempo
    uid: tempo-ds
    access: proxy
    url: http://tempo:3200
    jsonData:
      # Este bloque permite volver de una Traza -> Logs relacionados
      lokiSearch:
        datasourceUid: 'loki-ds'
      tracesToLogs:
        datasourceUid: 'loki-ds'
        filterBySpanID: false
        filterByTraceID: true
        mapTagNamesEnabled: true
