name: Deploy to AWS EC2

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: memoryonline-signalr
  CONTAINER_NAME: memoryonline-signalr
  EC2_PUBLIC_IP: "${{ secrets.EC2_PUBLIC_IP }}"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3

      - name: Build Docker image for ARM64
        run: |
          docker buildx build --platform linux/arm64 -t ${{ env.IMAGE_NAME }}:latest -f src/01.Apis/MemoryOnline.Apis.Signalr/Dockerfile --load .

      - name: Save Docker image as tar
        run: docker save ${{ env.IMAGE_NAME }}:latest | gzip > image.tar.gz

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "image.tar.gz,.github/scripts/deploy.sh"
          target: "/home/${{ secrets.EC2_USER }}"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          command_timeout: 10m
          script: |
            echo "📂 Preparando archivos..."
            echo "✅ Archivos listos"

            # Dar permisos y ejecutar script
            chmod +x /home/${{ secrets.EC2_USER }}/.github/scripts/deploy.sh

            echo "🚀 Ejecutando deploy.sh..."

            # Ejecutar con variables de entorno
            export CLOUDFLARE_TOKEN="${{ secrets.CLOUDFLARE_TOKEN }}"
            export EC2_USER="${{ secrets.EC2_USER }}"
            export CONTAINER_NAME="${{ env.CONTAINER_NAME }}"
            export IMAGE_NAME="${{ env.IMAGE_NAME }}"
            export DOMAIN="memoryec2.hispalance.com"

            /home/${{ secrets.EC2_USER }}/.github/scripts/deploy.sh

            echo "🧹 Limpiando..."
            rm -rf /home/${{ secrets.EC2_USER }}/.github
